#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set theme here because it uses kill signal USR1 which doesn't work as plugin theme and kills terminal
source ${HOME}/.zprezto/modules/prompt/external/bureau/prompt_bureau_setup.zsh


