#
# Custom zshrc
#
#


# Disable zsh autocorretion
unsetopt correct

# Load functions
fpath=( ${HOME}/.zprezto/custom/functions "${fpath[@]}" )

# Set theme here because it uses kill signal USR1 which doesn't work
# as plugin theme in zprezto and kills terminal because TRAPUSR1() not defined
source ${HOME}/.zprezto/custom/prompt/prompt_bureau_setup.zsh
source ${HOME}/.sdkman/bin/sdkman-init.sh
source ${HOME}/.zprezto/custom/k8s_zsh_functions

# Configure go
export PATH="${HOME}/code/gopath/bin:/usr/local/go/bin:${HOME}/bin:$PATH"
export GOPATH=${HOME}/code/gopath

# Stuff
export EDITOR=vim

# BTB specific stuff
if [[ -d "${GOPATH}/src/github.com/btb-gmbh/cloudnative/devEnv/scripts" ]]; then
  source ${GOPATH}/src/github.com/btb-gmbh/cloudnative/devEnv/scripts/exports.sh
  source ${GOPATH}/src/github.com/btb-gmbh/cloudnative/devEnv/scripts/aliases.sh
  source ${GOPATH}/src/github.com/btb-gmbh/cloudnative/devEnv/scripts/functions.zsh
  source ${HOME}/code/src/github.com/chkrde/devbox/scripts/btb-custom.zsh
  echo "BTB environment settings loaded..."
fi

# Aliases
alias vizshrc="vim ${HOME}/.zprezto/custom/zshrc"
alias vizpreztorc="vim ${HOME}/.zprezto/runcoms/zpreztorc"
alias godevbox="cd ${HOME}/code/src/github.com/chkrde/devbox"
alias code="code --disable-gpu"
alias history="history 1"

export GPG_TTY=$(tty)

